### ISSUE TITLE
Suggestion: multithread

### ISSUE THREAD

**Issue by invertdna** [LunaGal/rCRUX#1]
A suggestion to make `-num_threads` an argument to `blast_seeds()`. It's otherwise buried; I think the right core function would be `run_blastn()`, which is doing the actual `system2()` call to `blastn`.

**Comment by limey-bean** [comment]
Thanks for the suggestion!  We were using parallel::detectCores() to get the num_threads. The default will be to use detectCores(), but the user can now choose the number using num_threads for run_blastn() and run_primer_blastn().
