### ISSUE TITLE
ncbi path variable not carried forward?

### ISSUE THREAD

**Issue by invertdna** [LunaGal/rCRUX#2]
Getting this error in `blast_seeds()` after it successfully ran blastn; error happened after about an hour of runtime:

`The number of unsampled indices is less than or equal to the maximum number to be blasted
Running blastdbcmd on 1000 samples.
Calling blastn. This may take a long time.                                                                                                        
1969595 blast hits returned.
21715 unique blast hits after this round.
Error in system2("blastdbcmd", args = c("-db", blast_db_path, "-dbtype",  : 
  error in running command`

I'm thinking the `ncbi_bin` argument to `blast_seeds()` doesn't get scoped quite right, and so doesn't make it down to the function in which `system2("blastdbcmd")` gets called.

**Comment by limey-bean** [comment]
Thanks invertdna,  did the blast_seeds() run generate a blast_seeds_output directory with fasta and taxonomy files?  There is an error reporting issue for blastdbcmd that I am addressing, and I want to make sure this is not a new problem.

**Comment by invertdna** [comment]
It did generate a blast_seeds_output directory, but that directory is empty (I'm guessing because it ran into this path issue before completing the relevant steps?)

**Comment by limey-bean** [comment]
There is a convoluted while loop that is likely causing the error.  Could you send me the output written in the save directory?

**Comment by limey-bean** [comment]
Also, when did you install rCRUX?

**Comment by limey-bean** [comment]
We were able to reproduce your error. 

It was caused by bit of code that all accessions from NCBI that are collapsed into single record, and makes record for them. It is a helpful bit of code, it you are interested in identical sequence across taxa.  Apparently, it has memory problems...  I removed it, and will turn it into a new function ASAP. Thanks again for reporting it.
