### ISSUE TITLE
NCBI download code

### ISSUE THREAD

**Issue by ksilnoaa** [LunaGal/rCRUX#27]
NCBI just added some smaller nucleotide databases to the FTP site, so you can get one for just eukaryotes if you want ([see here](https://ncbiinsights.ncbi.nlm.nih.gov/2023/05/16/split-nucleotide-databases/). This also means the current code on the readme to download the nt database isn't quite right. If you just want the full nt database (not the partial databases), use this:

wget "ftp://ftp.ncbi.nlm.nih.gov/blast/db/nt.??.tar.gz*"

Having only the nt_euk DB might make COI a lot faster though...

**Comment by limey-bean** [comment]
many thanks!

That is true, database makes a lot of difference in build time.  It all depends on your specific goals for the database.  We have also had luck with custom database builds.
