### ISSUE TITLE
Default evalue for run_primer_blastn is 3e+07

### ISSUE THREAD

**Issue by ksilnoaa** [LunaGal/rCRUX#28]
The documentation states that the default e-value for run_primer_blast is 3e-07, but looking at the run_primer_blastn code it is 3e+07, which seems really high. Which one should it be?

**Comment by slambrechts** [comment]
I have the same question. Should probably be 3e-07... I assume we can specify it using evalue = 0.0000003?

**Comment by limey-bean** [comment]
Hi all,  Thanks for finding the typo in the documentation. The code is correct, it should be 3e+07.  The e-value was adjusted for blasting short reads.
